remote_theme: pages-themes/minimal@v0.2.0
title: Batool Abbas
logo: <img src="/assets/img/face.png" /></a>               
description: LinkedIn

name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/batool-abbas

plugins:
- jekyll-remote-theme
