remote_theme: pages-themes/minimal@v0.2.0
title: Batool Abbas
logo: <img src="/assets/img/face.png" /></a>               
description: <a href="https://www.linkedin.com/in/batool-abbas"><img src="https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/svgs/brands/linkedin.svg"></a>

plugins:
- jekyll-remote-theme
